name: LootChest
main: fr.black_eyes.lootchest.Main
version: 2.1.3
api-version: 1.13
softdepend: [MultiWorld, Multiverse-Core, FabledSkyBlock]
description: >
             Plugin for Regenerating Chests
commands:
  lootchest:
    description: Main Command
    aliases: lc